### ISSUE TITLE
[Bug] mod meun6.2.3 can't blender version 0.2.74+4879973

### ISSUE THREAD

**Issue by vocaloidkiss** [Nyan-Work/xaero-map-addition#1]
### Minecraft Version

1.19.4

### Xaero Map Addition Version

0.2.74+4879973

### Description

mod meun6.2.3 can't blender version 0.2.74+4879973

### To Reproduce

install mod meun6.2.3 and xaero-map-addition 0.2.74+4879973

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Any logs?
