### ISSUE TITLE
[Bug] 跟OMMC一样，与 Sodium 0.5.0 不兼容

### ISSUE THREAD

**Issue by DoYmL8c** [Nyan-Work/xaero-map-addition#4]
### Minecraft Version

1.20.1

### Xaero Map Addition Version

1.20.1-0.2.79+91bd337-beta

### Description

跟隔壁的OMMC一样，详情可看OMMC的issues

### To Reproduce

仅安装XMA和Sodium和必要的前置，打开游戏进入世界就会崩溃

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请先尝试更新 OMMC 至最新版本。

**Comment by DoYmL8c** [comment]
> 请先尝试更新 OMMC 至最新版本。

已得到修复，感谢你的维护。
