### ISSUE TITLE
[Bug] 1.20.1-0.2.86+85478ec-beta与Xaeros_Minimap_23.9.0_Fabric_1.20不兼容

### ISSUE THREAD

**Issue by vocaloidkiss** [Nyan-Work/xaero-map-addition#7]
### Minecraft Version

JAVA fabric loader0.14.24 1.20.1

### Xaero Map Addition Version

0.2.86+85478ec-beta

### Description

1.20.1-0.2.86+85478ec-beta与Xaeros_Minimap_23.9.0_Fabric_1.20不兼容

### To Reproduce

安装XMA XMM OMMC 启动时崩溃

### Log

[crash-2023-11-28_07.49.10-client.txt](https://github.com/Nyan-Work/xaero-map-addition/files/13481770/crash-2023-11-28_07.49.10-client.txt)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请尝试：[0.2.87+de2b3ab](https://github.com/Nyan-Work/xaero-map-addition/releases/tag/nyan-work%2Fdev.15)
